version: '3.8'

services:
  db:
    build: .
    container_name: eco-games-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: eco_games_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
